### ISSUE TITLE
new section proposal

### ISSUE THREAD

**Issue by binarymist** [devsecops/awesome-devsecops#12]
Thought of adding a section for books, trainings, etc?

**Comment by slietz** [comment]
@binarymist - we'd love to get a list of helpful books.  The current #Training section does not yet have that section and can be added.  We have found few resources to list so far in the category of books.  Please send a pull request if you have found some useful for the community.

**Comment by binarymist** [comment]
I see you have DevSecCon in there, I'm doing a training there in a few days, and will be interviewing the organiser on a show called DevSecOps for Software Engineering Radio, keep an eye out for that one in a couple of months.

In regards to books, I'm working on a book series that is all DevSecOps, I just never realised it had been formalised as a thing.

**Comment by slietz** [comment]
@binarymist - sounds good.  See you there ;-)

**Comment by binarymist** [comment]
I wonder if it's worth adding short descriptions beside links, like many other awesome lists do. Just to give the reader a bit of an idea what the offering is all about?

**Comment by slietz** [comment]
@binarymist - that would be lovely!

**Comment by binarymist** [comment]
Maybe add it to the CONTRIBUTING.md?

**Comment by slietz** [comment]
Added section for books.  Closed, no additional action.
