### ISSUE TITLE
Add things like Threatstack and Twistlock

### ISSUE THREAD

**Issue by InAnimaTe** [devsecops/awesome-devsecops#34]
These fit into the modern microservices model relatively well and are growing.

**Comment by slietz** [comment]
do they have community versions or anything to help folks learn?

**Comment by slietz** [comment]
Needs to have a free/community version or other tool the community can work with.

**Comment by InAnimaTe** [comment]
Ok well disregard then. Not sure how only "Free or Open Source capabilities" based solutions are the ones to help with the "DevSecOps mission". There can be great services and solutions that are closed source but still help protect infrastructure and modern DevOps technologies.

**Comment by slietz** [comment]
Not disregarding them.  We are not making this list about free or open source, it's about making resources available to everyone for learning and maturing your approach.  For these two companies, we did not find available tools for folks to learn from that are freely available before having to commit to the sales cycle.  That said, Twistlock has an ebook available for people to download that would be great to add:  https://www.twistlock.com/resources/kubernetes-deployment-security-patterns/ AND we think that Threatstack may have some resources to learn from in terms of talks but it was hard to discern through all their marketecture.  Feel free to make a PR if you find useful things that can help everyone without this list becoming simply another vehicle for advertising.
